export const DEMO = {
  CLEAR_REMARK: 'CLEAR_REMARK',
  UPDATE_REMARK: 'UPDATE_REMARK',
  UPDATE_REMARK_F: 'UPDATE_REMARK_F',
  UPDATE_LOCAL: 'UPDATE_LOCAL',
  UPDATE_USERINFO: 'UPDATE_USERINFO'
}
export const OTHER2 = {
  RECORD_ADDRESS2: 'RECORD_ADDRESS',
  UPDATE_LOCAL2: 'UPDATE_LOCAL'
}
export const QRCODE = {
  COMMIT_LOGINNAME: 'COMMIT_LOGINNAME'
}
